 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: shipping-service-deployment
   namespace: dicoding
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: shipping-service
   template:
     metadata:
       labels:
         app: shipping-service
     spec:
       containers:
         - name: shipping-service
           image: 23pstars/shipping-service:latest
           ports:
             - containerPort: 3001
           env:
             - name: AMQP_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: my-rabbitmq
                   key: rabbitmq-password
             - name: AMQP_URL
               value: "amqp://user:$(AMQP_PASSWORD)@my-rabbitmq:5672"
